[package]
name = "autopilot"
version.workspace = true
edition.workspace = true

[[bin]]
name = "autopilot"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
autopilot-camera.workspace = true
autopilot-config.workspace = true
autopilot-input.workspace = true
autopilot-model.workspace = true
autopilot-stream.workspace = true
autopilot-vision.workspace = true
autopilot-vesc.workspace = true
clap.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
ctrlc = "3"
